apiVersion: v1
kind: Service
metadata:
  name: chatapp-gateway-service
  namespace: chatapp-namespace
spec:
  type: LoadBalancer
  selector:
    app: chatapp-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081