apiVersion: v1
kind: Service
metadata:
  name: chatapp-gateway-service
spec:
  type: LoadBalancer
  selector:
    app: chatapp-gateway-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081